language: rust
sudo: false # <-- always goodness
cache: cargo
rust:
  - nightly
jobs:
  include:
    - stage: "Build and Test"
      name: "Build"
      script: cargo build --verbose --all
    - script: cargo test --verbose --all
      name: "Test"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        # api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
