[package]
name = "lunatic-runtime"
version = "0.3.2"
authors = ["Bernard Kolobara <me@kolobara.com>"]
edition = "2018"
description = "An actor platform built on WebAssembly"
license = "Apache-2.0/MIT"
readme = "Readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lunatic_runtime"
path = "src/lib.rs"

[[bin]]
name = "lunatic"
path = "src/main.rs"

[features]
default = ["vm-wasmer"]
vm-wasmtime = ["uptown_funk/vm-wasmtime", "wasmtime", "wasmtime-runtime"]
vm-wasmer = ["uptown_funk/vm-wasmer", "wasmer", "wasmer-vm"]

[dependencies]
async-wormhole = "0.3"
uptown_funk = { version = "0.1", path = "./uptown_funk", features=["async"] }
libc = { version = "^0.2", default-features = false }
wasmer = { git = "https://github.com/lunatic-solutions/wasmer.git", branch = "lunatic", optional = true }
wasmer-vm = { git = "https://github.com/lunatic-solutions/wasmer.git", branch = "lunatic", optional = true }
wasmtime = { git = "https://github.com/lunatic-solutions/wasmtime.git", branch = "lunatic", optional = true }
wasmtime-runtime = { git = "https://github.com/lunatic-solutions/wasmtime.git", branch = "lunatic", optional = true }
clap = "3.0.0-beta.2"
getrandom = { version = "0.2.0", features = ["std"] }
walrus = "0.18"
smol = "1.2"
easy-parallel = "3"
anyhow = "1.0"
lazy_static = "1.4.0"
smallvec = "1.5"
env_logger = "0.8"
log = "0.4"

[dev-dependencies]
criterion = "0.3"
rayon = "1.5"
wat = "1.0"
wasmprinter = "0.2"
pretty_assertions = "0.6.1"

[[bench]]
name = "lunatic_benchmark"
harness = false

[[test]]
name = "normalisation_patching_test"
harness = false
